select a.brand, a.region, count(distinct a.best_mobile_number_hash)
from (select case when lower(a.brand) like 'clinic%' then 'Clinic'
when lower(a.brand) like 'clear%' then 'Clear'
when lower(a.brand) like '%all%cl%' then 'Clear'
when lower(a.brand) like 'lux%' then 'Lux'
when lower(a.brand) like 'pond%' then 'Ponds'
when lower(a.brand) like 'vasel%' then 'Vaseline'
when lower(a.brand) like 'rin%' then 'RIN'
when lower(a.brand) like 'vim%' then 'Vim'
when lower(a.brand) like 'f&l%' then 'Fair & Lovely'
when lower(a.brand) like 'fal%' then 'Fair & Lovely'
when lower(a.brand) like 'fl%' then 'Fair & Lovely'
when lower(a.brand) like '%fair%love%' then 'Fair & Lovely'
when lower(a.brand) like 'bru%' then 'Bru'
when lower(a.brand) like 'coffee%' then 'Bru'
when lower(a.brand) like '%surf%' then 'Surf Excel'
when lower(a.brand) like 'vim%' then 'Vim'
when lower(a.brand) like '%vim%' then 'Vim'
when lower(a.brand) like 'axe%' then 'Axe'
when lower(a.brand) like 'close%' then 'Close UP'
when lower(a.brand) like 'comfor%' then 'Comfort'
when lower(a.brand) like 'domex%' then 'Domex'
when lower(a.brand) like 'doemx%' then 'Domex'
when lower(a.brand) like 'dmx%' then 'Domex'
when lower(a.brand) like 'dove%' then 'Dove'
when lower(a.brand) like 'kissan%' then 'Kissan'
when lower(a.brand) like '%ketchup%' then 'Kissan'
when lower(a.brand) like 'knor%' then 'Knorr'
when lower(a.brand) like 'kw%' then 'Kwality Wall''s'
when lower(a.brand) like 'liri%' then 'Liril'
when lower(a.brand) like 'pear%' then 'Pears'
when lower(a.brand) like 'pep%' then 'Pepsodent'
when lower(a.brand) like 'trese%' then 'Tresemme'
when lower(a.brand) like 'sunsil%' then 'Sunsilk'
when lower(a.brand) like '%taj%' then 'Taj mahal'
when lower(a.brand) like 'tigi%' then 'TIGI'
when lower(a.brand) like 'avian%' then 'Aviance'
when lower(a.brand) like 'cornetto%' then 'Cornetto'
when lower(a.brand) like '' then ''
else 'Others' end as brand,b.region, a.best_mobile_number_hash
from PRM.h2h_transaction a
inner join PRM.ref_mobile_lookup b
on a.region_lookup_number=b.lookup_prefix5
where b.region='Mumbai'
union 
select case when lower(a.brand) like 'clinic%' then 'Clinic'
when lower(a.brand) like 'clear%' then 'Clear'
when lower(a.brand) like '%all%cl%' then 'Clear'
when lower(a.brand) like 'lux%' then 'Lux'
when lower(a.brand) like 'pond%' then 'Ponds'
when lower(a.brand) like 'vasel%' then 'Vaseline'
when lower(a.brand) like 'rin%' then 'RIN'
when lower(a.brand) like 'vim%' then 'Vim'
when lower(a.brand) like 'f&l%' then 'Fair & Lovely'
when lower(a.brand) like 'fal%' then 'Fair & Lovely'
when lower(a.brand) like 'fl%' then 'Fair & Lovely'
when lower(a.brand) like '%fair%love%' then 'Fair & Lovely'
when lower(a.brand) like 'bru%' then 'Bru'
when lower(a.brand) like 'coffee%' then 'Bru'
when lower(a.brand) like '%surf%' then 'Surf Excel'
when lower(a.brand) like 'vim%' then 'Vim'
when lower(a.brand) like '%vim%' then 'Vim'
when lower(a.brand) like 'axe%' then 'Axe'
when lower(a.brand) like 'close%' then 'Close UP'
when lower(a.brand) like 'comfor%' then 'Comfort'
when lower(a.brand) like 'domex%' then 'Domex'
when lower(a.brand) like 'doemx%' then 'Domex'
when lower(a.brand) like 'dmx%' then 'Domex'
when lower(a.brand) like 'dove%' then 'Dove'
when lower(a.brand) like 'kissan%' then 'Kissan'
when lower(a.brand) like '%ketchup%' then 'Kissan'
when lower(a.brand) like 'knor%' then 'Knorr'
when lower(a.brand) like 'kw%' then 'Kwality Wall''s'
when lower(a.brand) like 'liri%' then 'Liril'
when lower(a.brand) like 'pear%' then 'Pears'
when lower(a.brand) like 'pep%' then 'Pepsodent'
when lower(a.brand) like 'trese%' then 'Tresemme'
when lower(a.brand) like 'sunsil%' then 'Sunsilk'
when lower(a.brand) like '%taj%' then 'Taj mahal'
when lower(a.brand) like 'tigi%' then 'TIGI'
when lower(a.brand) like 'avian%' then 'Aviance'
when lower(a.brand) like 'cornetto%' then 'Cornetto'
when lower(a.brand) like '' then ''
else 'Others' end as brand,b.region, a.best_mobile_number_hash
from PRM.mindtree_data a
inner join PRM.ref_mobile_lookup b
on a.region_lookup_number=b.lookup_prefix5
where b.region='Mumbai') as a
group by 1,2 



 select 
    distinct 'IN' as market
    , 'H2H' as provider
	, a.best_mobile_number_hash as mobileno
	, '1' as optin_hierarchy_level
	, 'Unilever' as optin_hierarchy_value
from (select case when lower(a.brand) like 'clinic%' then 'Clinic'
when lower(a.brand) like 'clear%' then 'Clear'
when lower(a.brand) like '%all%cl%' then 'Clear'
when lower(a.brand) like 'lux%' then 'Lux'
when lower(a.brand) like 'pond%' then 'Ponds'
when lower(a.brand) like 'vasel%' then 'Vaseline'
when lower(a.brand) like 'rin%' then 'RIN'
when lower(a.brand) like 'vim%' then 'Vim'
when lower(a.brand) like 'f&l%' then 'Fair & Lovely'
when lower(a.brand) like 'fal%' then 'Fair & Lovely'
when lower(a.brand) like 'fl%' then 'Fair & Lovely'
when lower(a.brand) like '%fair%love%' then 'Fair & Lovely'
when lower(a.brand) like 'bru%' then 'Bru'
when lower(a.brand) like 'coffee%' then 'Bru'
when lower(a.brand) like '%surf%' then 'Surf Excel'
when lower(a.brand) like 'vim%' then 'Vim'
when lower(a.brand) like '%vim%' then 'Vim'
when lower(a.brand) like 'axe%' then 'Axe'
when lower(a.brand) like 'close%' then 'Close UP'
when lower(a.brand) like 'comfor%' then 'Comfort'
when lower(a.brand) like 'domex%' then 'Domex'
when lower(a.brand) like 'doemx%' then 'Domex'
when lower(a.brand) like 'dmx%' then 'Domex'
when lower(a.brand) like 'dove%' then 'Dove'
when lower(a.brand) like 'kissan%' then 'Kissan'
when lower(a.brand) like '%ketchup%' then 'Kissan'
when lower(a.brand) like 'knor%' then 'Knorr'
when lower(a.brand) like 'kw%' then 'Kwality Wall''s'
when lower(a.brand) like 'liri%' then 'Liril'
when lower(a.brand) like 'pear%' then 'Pears'
when lower(a.brand) like 'pep%' then 'Pepsodent'
when lower(a.brand) like 'trese%' then 'Tresemme'
when lower(a.brand) like 'sunsil%' then 'Sunsilk'
when lower(a.brand) like '%taj%' then 'Taj mahal'
when lower(a.brand) like 'tigi%' then 'TIGI'
when lower(a.brand) like 'avian%' then 'Aviance'
when lower(a.brand) like 'cornetto%' then 'Cornetto'
when lower(a.brand) like '' then ''
else 'Others' end as brand,b.region, a.best_mobile_number_hash
from PRM.h2h_transaction a
inner join PRM.ref_mobile_lookup b
on a.region_lookup_number=b.lookup_prefix5
where b.region='Mumbai'
and (lower(a.brand) like 'clinic%' 
or lower(a.brand) like 'clear%'
or lower(a.brand) like '%all%cl%' 
or lower(a.brand) like 'lux%' 
or lower(a.brand) like 'pond%'
or lower(a.brand) like 'vasel%' 
or lower(a.brand) like 'rin%' 
or lower(a.brand) like 'vim%'
or lower(a.brand) like 'f&l%' 
or lower(a.brand) like 'fal%' 
or lower(a.brand) like 'fl%' 
or lower(a.brand) like '%fair%love%' 
or lower(a.brand) like 'bru%' 
or lower(a.brand) like 'coffee%' 
or lower(a.brand) like '%surf%'
or lower(a.brand) like 'vim%' 
or lower(a.brand) like '%vim%' 
or lower(a.brand) like 'axe%' 
or lower(a.brand) like 'close%' 
or lower(a.brand) like 'comfor%'
or lower(a.brand) like 'domex%' 
or lower(a.brand) like 'doemx%'
or lower(a.brand) like 'dmx%' 
or lower(a.brand) like 'dove%'
or lower(a.brand) like 'kissan%' 
or lower(a.brand) like '%ketchup%' 
or lower(a.brand) like 'knor%' 
or lower(a.brand) like 'kw%' 
or lower(a.brand) like 'liri%'
or lower(a.brand) like 'pear%'
or lower(a.brand) like 'pep%' 
or lower(a.brand) like 'trese%' 
or lower(a.brand) like 'sunsil%' 
or lower(a.brand) like '%taj%' 
or lower(a.brand) like 'tigi%' 
or lower(a.brand) like 'avian%' 
or lower(a.brand) like 'cornetto%' )
union 
select case when lower(a.brand) like 'clinic%' then 'Clinic'
when lower(a.brand) like 'clear%' then 'Clear'
when lower(a.brand) like '%all%cl%' then 'Clear'
when lower(a.brand) like 'lux%' then 'Lux'
when lower(a.brand) like 'pond%' then 'Ponds'
when lower(a.brand) like 'vasel%' then 'Vaseline'
when lower(a.brand) like 'rin%' then 'RIN'
when lower(a.brand) like 'vim%' then 'Vim'
when lower(a.brand) like 'f&l%' then 'Fair & Lovely'
when lower(a.brand) like 'fal%' then 'Fair & Lovely'
when lower(a.brand) like 'fl%' then 'Fair & Lovely'
when lower(a.brand) like '%fair%love%' then 'Fair & Lovely'
when lower(a.brand) like 'bru%' then 'Bru'
when lower(a.brand) like 'coffee%' then 'Bru'
when lower(a.brand) like '%surf%' then 'Surf Excel'
when lower(a.brand) like 'vim%' then 'Vim'
when lower(a.brand) like '%vim%' then 'Vim'
when lower(a.brand) like 'axe%' then 'Axe'
when lower(a.brand) like 'close%' then 'Close UP'
when lower(a.brand) like 'comfor%' then 'Comfort'
when lower(a.brand) like 'domex%' then 'Domex'
when lower(a.brand) like 'doemx%' then 'Domex'
when lower(a.brand) like 'dmx%' then 'Domex'
when lower(a.brand) like 'dove%' then 'Dove'
when lower(a.brand) like 'kissan%' then 'Kissan'
when lower(a.brand) like '%ketchup%' then 'Kissan'
when lower(a.brand) like 'knor%' then 'Knorr'
when lower(a.brand) like 'kw%' then 'Kwality Wall''s'
when lower(a.brand) like 'liri%' then 'Liril'
when lower(a.brand) like 'pear%' then 'Pears'
when lower(a.brand) like 'pep%' then 'Pepsodent'
when lower(a.brand) like 'trese%' then 'Tresemme'
when lower(a.brand) like 'sunsil%' then 'Sunsilk'
when lower(a.brand) like '%taj%' then 'Taj mahal'
when lower(a.brand) like 'tigi%' then 'TIGI'
when lower(a.brand) like 'avian%' then 'Aviance'
when lower(a.brand) like 'cornetto%' then 'Cornetto'
when lower(a.brand) like '' then ''
else 'Others' end as brand,b.region, a.best_mobile_number_hash
from PRM.mindtree_data a
inner join PRM.ref_mobile_lookup b
on a.region_lookup_number=b.lookup_prefix5
where b.region='Mumbai' and (lower(a.brand) like 'clinic%' 
or lower(a.brand) like 'clear%'
or lower(a.brand) like '%all%cl%' 
or lower(a.brand) like 'lux%' 
or lower(a.brand) like 'pond%'
or lower(a.brand) like 'vasel%' 
or lower(a.brand) like 'rin%' 
or lower(a.brand) like 'vim%'
or lower(a.brand) like 'f&l%' 
or lower(a.brand) like 'fal%' 
or lower(a.brand) like 'fl%' 
or lower(a.brand) like '%fair%love%' 
or lower(a.brand) like 'bru%' 
or lower(a.brand) like 'coffee%' 
or lower(a.brand) like '%surf%'
or lower(a.brand) like 'vim%' 
or lower(a.brand) like '%vim%' 
or lower(a.brand) like 'axe%' 
or lower(a.brand) like 'close%' 
or lower(a.brand) like 'comfor%'
or lower(a.brand) like 'domex%' 
or lower(a.brand) like 'doemx%'
or lower(a.brand) like 'dmx%' 
or lower(a.brand) like 'dove%'
or lower(a.brand) like 'kissan%' 
or lower(a.brand) like '%ketchup%' 
or lower(a.brand) like 'knor%' 
or lower(a.brand) like 'kw%' 
or lower(a.brand) like 'liri%'
or lower(a.brand) like 'pear%'
or lower(a.brand) like 'pep%' 
or lower(a.brand) like 'trese%' 
or lower(a.brand) like 'sunsil%' 
or lower(a.brand) like '%taj%' 
or lower(a.brand) like 'tigi%' 
or lower(a.brand) like 'avian%' 
or lower(a.brand) like 'cornetto%' )
) as a;







 