--kkt age

select b.region,count(distinct best_mobile_number_hash) as counts
from (select distinct best_mobile_number_hash,region_lookup_number from PRM.kkt_cdr_contest_trans_ST
where contest_file_id = 10 and option_provided not in (0,1,2)
union all 
select distinct best_mobile_number_hash,region_lookup_number from PRM.kkt_cdrl_contest
where contest_file_id = 10 and option_provided not in (0,1,2)) a
inner join PRM.ref_mobile_lookup b on a.region_lookup_number = b.lookup_prefix5
where b.region in ('Delhi','Mumbai','Kolkata','Chennai')
and best_mobile_number_hash in (select count(distinct best_mobile_number_hash) from (
select distinct best_mobile_number_hash from PRM.kkt_cdr_contest_trans_ST
where contest_file_id = 9 and option_provided = 1
union all 
select distinct best_mobile_number_hash from PRM.kkt_cdrl_contest
where contest_file_id = 9 and option_provided = 1) as a)
group by 1;


--lakme base
select case when lower(city) like 'bangalu%' then 'Bengaluru'
when lower(city) like 'bangalo%' then 'Bengaluru'
when lower(city) like 'banagal%' then 'Bengaluru'
when lower(city) like 'bengalu%' then 'Bengaluru'
when lower(city) like 'bangalo%' then 'Bengaluru'
when lower(city) like 'bangl%' then 'Bengaluru'
when lower(city) like 'bengl%' then 'Bengaluru'
when lower(city) like 'bango%' then 'Bengaluru'
when lower(city) like 'bangu%' then 'Bengaluru'
when lower(city) like 'blr%' then 'Bengaluru'
when lower(city) like 'bnag%' then 'Bengaluru'
when lower(city) like 'blore%' then 'Bengaluru'
when lower(city) like 'hyder%' then 'Hyderbad'
when lower(city) like 'hydra%' then 'Hyderbad'
when lower(city) like 'puna%' then 'Pune'
when lower(city) like 'poona%' then 'Pune'
when lower(city) like 'pune%' then 'Pune'
when lower(city) like 'ahmed%' then 'Ahemdabad'
when lower(city) like 'ahmad%' then 'Ahemdabad'
when lower(city) like 'ahmd%' then 'Ahemdabad'
when lower(city) like 'aham%' then 'Ahemdabad'
when lower(city) like 'ahem%' then 'Ahemdabad' 
end as City, count(distinct best_mobile_number_hash) from PRM.lk_customer
where lower(gender)  like 'mal%'
and length(date_of_birth) > 4
and (date_of_birth like '%1991%' or date_of_birth like '%1990%' 
or date_of_birth like '%198%' or date_of_birth like '%197%'
or date_of_birth like '%196%' or date_of_birth like '%195%')
and (lower(city) like 'bangalu%' 
or lower(city) like 'bangalo%' 
or lower(city) like 'banagal%' 
or lower(city) like 'bengalu%' 
or lower(city) like 'bangalo%' 
or lower(city) like 'bangl%' 
or lower(city) like 'bengl%' 
or lower(city) like 'bango%' 
or lower(city) like 'bangu%' 
or lower(city) like 'blr%' 
or lower(city) like 'bnag%' 
or lower(city) like 'blore%' 
or lower(city) like 'hyder%' 
or lower(city) like 'hydra%' 
or lower(city) like 'puna%' 
or lower(city) like 'poona%' 
or lower(city) like 'pune%' 
or lower(city) like 'ahmed%' 
or lower(city) like 'ahmad%' 
or lower(city) like 'ahmd%' 
or lower(city) like 'aham%' 
or lower(city) like 'ahem%')
group by 1

union all
select b.region, count(distinct best_mobile_number_hash) from PRM.lk_customer a
inner join PRM.ref_mobile_lookup b on a.region_lookup_number = b.lookup_prefix5
where lower(gender)  like 'mal%'
and length(date_of_birth) > 4
and (date_of_birth like '%1991%' or date_of_birth like '%1990%' 
or date_of_birth like '%198%' or date_of_birth like '%197%'
or date_of_birth like '%196%' or date_of_birth like '%195%')
and b.region in ('Delhi','Mumbai','Kolkata','Chennai')
group by 1;


--h2h base
select case 
when lower(brand) like '%3 rose%' then '3 Roses'
when lower(brand) like '%axe%' then 'Axe'
when lower(brand) like '%bedhead%' then 'Beadhead'
when lower(brand) like '%bru%' then 'Bru'
when lower(brand) like '%brook%' then 'Brooke Bond'
when lower(brand) like '%clear%' then 'Clear'
when lower(brand) like '%clinic%' then 'Clinic'
when lower(brand) like '%close%' then 'Close UP'
when lower(brand) like '%comfo%' then 'Comfort'
when lower(brand) like '%cornet%' then 'Cornetto'
when lower(brand) like '%dome%' then 'Domex'
when lower(brand) like '%dove%' then 'Dove'
when lower(brand) like '%dream%' then 'Dreamflower'
when lower(brand) like '%ell %' then 'Ell 18'
when lower(brand) like '%f&l%' then 'Fair & Lovely'
when lower(brand) like '%fal%' then 'Fair & Lovely'
when lower(brand) like '%fl%' then 'Fair & Lovely'
when lower(brand) like '%fair%love%' then 'Fair & Lovely'
when lower(brand) like '%kissan%' then 'Kissan'
when lower(brand) like '%kkt%' then 'KKT'
when lower(brand) like '%knor%' then 'Knorr'
when lower(brand) like '%kwali%' then 'Kwality Wall''s'
when lower(brand) like '%liri%' then 'Liril'
when lower(brand) like '%lakm%' then 'Lakme'
when lower(brand) like '%lifeb%' then 'Lifebuoy'
when lower(brand) like '%lipt%' then 'Lipton'
when lower(brand) like '%lux%' then 'Lux'
when lower(brand) like '%pear%' then 'Pears'
when lower(brand) like '%pepso%' then 'Pepsodent'
when lower(brand) like '%pond%' then 'Ponds'
when lower(brand) like '%pure%' then 'PureIT'
when lower(brand) like '%red%lab%' then 'Red label'
when lower(brand) like '%rin%' then 'Rin'
when lower(brand) like '%sunlig%' then 'Sunlight'
when lower(brand) like '%sunsi%' then 'Sunsilk'
when lower(brand) like '%surf%' then 'Surf Excel'
when lower(brand) like '%taaza%' then 'Taaza'
when lower(brand) like '%taj%' then 'Taj Mahal'
when lower(brand) like '%tigi%' then 'TIGI'
when lower(brand) like '%trese%' then 'Tresemme'
when lower(brand) like '%vaseli%' then 'Vaseline'
when lower(brand) like '%vim%' then 'Vim'
when lower(brand) like '%wheel%' then 'Wheel'
else lower(brand)
end as "Brand",
case when lower(city) like 'bangalu%' then 'Bengaluru'
when lower(city) like 'bangalo%' then 'Bengaluru'
when lower(city) like 'banagal%' then 'Bengaluru'
when lower(city) like 'bengalu%' then 'Bengaluru'
when lower(city) like 'bangalo%' then 'Bengaluru'
when lower(city) like 'bangl%' then 'Bengaluru'
when lower(city) like 'bengl%' then 'Bengaluru'
when lower(city) like 'bango%' then 'Bengaluru'
when lower(city) like 'bangu%' then 'Bengaluru'
when lower(city) like 'blr%' then 'Bengaluru'
when lower(city) like 'bnag%' then 'Bengaluru'
when lower(city) like 'blore%' then 'Bengaluru'
when lower(city) like 'hyder%' then 'Hyderbad'
when lower(city) like 'hydra%' then 'Hyderbad'
when lower(city) like 'puna%' then 'Pune'
when lower(city) like 'poona%' then 'Pune'
when lower(city) like 'pune%' then 'Pune'
when lower(city) like 'ahmed%' then 'Ahemdabad'
when lower(city) like 'ahmad%' then 'Ahemdabad'
when lower(city) like 'ahmd%' then 'Ahemdabad'
when lower(city) like 'aham%' then 'Ahemdabad'
when lower(city) like 'ahem%' then 'Ahemdabad' 
end as City, count(distinct best_mobile_number_hash) from PRM.h2h_transaction
where (lower(city) like 'bangalu%' 
or lower(city) like 'bangalo%' 
or lower(city) like 'banagal%' 
or lower(city) like 'bengalu%' 
or lower(city) like 'bangalo%' 
or lower(city) like 'bangl%' 
or lower(city) like 'bengl%' 
or lower(city) like 'bango%' 
or lower(city) like 'bangu%' 
or lower(city) like 'blr%' 
or lower(city) like 'bnag%' 
or lower(city) like 'blore%' 
or lower(city) like 'hyder%' 
or lower(city) like 'hydra%' 
or lower(city) like 'puna%' 
or lower(city) like 'poona%' 
or lower(city) like 'pune%' 
or lower(city) like 'ahmed%' 
or lower(city) like 'ahmad%' 
or lower(city) like 'ahmd%' 
or lower(city) like 'aham%' 
or lower(city) like 'ahem%')
and (lower(brand) like '%3 rose%' 
or lower(brand) like '%axe%' 
or lower(brand) like '%bedhead%' 
or lower(brand) like '%bru%' 
or lower(brand) like '%brook%' 
or lower(brand) like '%clear%' 
or lower(brand) like '%clinic%' 
or lower(brand) like '%close%' 
or lower(brand) like '%comfo%' 
or lower(brand) like '%cornet%' 
or lower(brand) like '%dome%' 
or lower(brand) like '%dove%' 
or lower(brand) like '%dream%' 
or lower(brand) like '%ell %' 
or lower(brand) like '%f&l%' 
or lower(brand) like '%fal%' 
or lower(brand) like '%fl%' 
or lower(brand) like '%fair%love%'
or lower(brand) like '%kissan%' 
or lower(brand) like '%kkt%' 
or lower(brand) like '%knor%' 
or lower(brand) like '%kwali%' 
or lower(brand) like '%liri%' 
or lower(brand) like '%lakm%' 
or lower(brand) like '%lifeb%' 
or lower(brand) like '%lipt%' 
or lower(brand) like '%lux%'  
or lower(brand) like '%pear%' 
or lower(brand) like '%pepso%' 
or lower(brand) like '%pond%' 
or lower(brand) like '%pure%' 
or lower(brand) like '%red%lab%' 
or lower(brand) like '%rin%'  
or lower(brand) like '%sunlig%' 
or lower(brand) like '%sunsi%' 
or lower(brand) like '%surf%' 
or lower(brand) like '%taaza%' 
or lower(brand) like '%taj%'  
or lower(brand) like '%tigi%' 
or lower(brand) like '%trese%' 
or lower(brand) like '%vaseli%' 
or lower(brand) like '%vim%'  
or lower(brand) like '%wheel%')
group by 1,2

union all
select case 
when lower(brand) like '%3 rose%' then '3 Roses'
when lower(brand) like '%axe%' then 'Axe'
when lower(brand) like '%bedhead%' then 'Beadhead'
when lower(brand) like '%bru%' then 'Bru'
when lower(brand) like '%brook%' then 'Brooke Bond'
when lower(brand) like '%clear%' then 'Clear'
when lower(brand) like '%clinic%' then 'Clinic'
when lower(brand) like '%close%' then 'Close UP'
when lower(brand) like '%comfo%' then 'Comfort'
when lower(brand) like '%cornet%' then 'Cornetto'
when lower(brand) like '%dome%' then 'Domex'
when lower(brand) like '%dove%' then 'Dove'
when lower(brand) like '%dream%' then 'Dreamflower'
when lower(brand) like '%ell %' then 'Ell 18'
when lower(brand) like '%f&l%' then 'Fair & Lovely'
when lower(brand) like '%fal%' then 'Fair & Lovely'
when lower(brand) like '%fl%' then 'Fair & Lovely'
when lower(brand) like '%fair%love%' then 'Fair & Lovely'
when lower(brand) like '%kissan%' then 'Kissan'
when lower(brand) like '%kkt%' then 'KKT'
when lower(brand) like '%knor%' then 'Knorr'
when lower(brand) like '%kwali%' then 'Kwality Wall''s'
when lower(brand) like '%liri%' then 'Liril'
when lower(brand) like '%lakm%' then 'Lakme'
when lower(brand) like '%lifeb%' then 'Lifebuoy'
when lower(brand) like '%lipt%' then 'Lipton'
when lower(brand) like '%lux%' then 'Lux'
when lower(brand) like '%pear%' then 'Pears'
when lower(brand) like '%pepso%' then 'Pepsodent'
when lower(brand) like '%pond%' then 'Ponds'
when lower(brand) like '%pure%' then 'PureIT'
when lower(brand) like '%red%lab%' then 'Red label'
when lower(brand) like '%rin%' then 'Rin'
when lower(brand) like '%sunlig%' then 'Sunlight'
when lower(brand) like '%sunsi%' then 'Sunsilk'
when lower(brand) like '%surf%' then 'Surf Excel'
when lower(brand) like '%taaza%' then 'Taaza'
when lower(brand) like '%taj%' then 'Taj Mahal'
when lower(brand) like '%tigi%' then 'TIGI'
when lower(brand) like '%trese%' then 'Tresemme'
when lower(brand) like '%vaseli%' then 'Vaseline'
when lower(brand) like '%vim%' then 'Vim'
when lower(brand) like '%wheel%' then 'Wheel'
else lower(brand)
end as "Brand",
b.region, count(distinct best_mobile_number_hash) from PRM.h2h_transaction a
inner join PRM.ref_mobile_lookup b on a.region_lookup_number = b.lookup_prefix5
where  b.region in ('Delhi','Mumbai','Kolkata','Chennai')
and (lower(brand) like '%3 rose%' 
or lower(brand) like '%axe%' 
or lower(brand) like '%bedhead%' 
or lower(brand) like '%bru%' 
or lower(brand) like '%brook%' 
or lower(brand) like '%clear%' 
or lower(brand) like '%clinic%' 
or lower(brand) like '%close%' 
or lower(brand) like '%comfo%' 
or lower(brand) like '%cornet%' 
or lower(brand) like '%dome%' 
or lower(brand) like '%dove%' 
or lower(brand) like '%dream%' 
or lower(brand) like '%ell %' 
or lower(brand) like '%f&l%' 
or lower(brand) like '%fal%' 
or lower(brand) like '%fl%' 
or lower(brand) like '%fair%love%'
or lower(brand) like '%kissan%' 
or lower(brand) like '%kkt%' 
or lower(brand) like '%knor%' 
or lower(brand) like '%kwali%' 
or lower(brand) like '%liri%' 
or lower(brand) like '%lakm%' 
or lower(brand) like '%lifeb%' 
or lower(brand) like '%lipt%' 
or lower(brand) like '%lux%'  
or lower(brand) like '%pear%' 
or lower(brand) like '%pepso%' 
or lower(brand) like '%pond%' 
or lower(brand) like '%pure%' 
or lower(brand) like '%red%lab%' 
or lower(brand) like '%rin%'  
or lower(brand) like '%sunlig%' 
or lower(brand) like '%sunsi%' 
or lower(brand) like '%surf%' 
or lower(brand) like '%taaza%' 
or lower(brand) like '%taj%'  
or lower(brand) like '%tigi%' 
or lower(brand) like '%trese%' 
or lower(brand) like '%vaseli%' 
or lower(brand) like '%vim%'  
or lower(brand) like '%wheel%')
group by 1,2

union all

select case 
when lower(brand) like '%3 rose%' then '3 Roses'
when lower(brand) like '%axe%' then 'Axe'
when lower(brand) like '%bedhead%' then 'Beadhead'
when lower(brand) like '%bru%' then 'Bru'
when lower(brand) like '%brook%' then 'Brooke Bond'
when lower(brand) like '%clear%' then 'Clear'
when lower(brand) like '%clinic%' then 'Clinic'
when lower(brand) like '%close%' then 'Close UP'
when lower(brand) like '%comfo%' then 'Comfort'
when lower(brand) like '%cornet%' then 'Cornetto'
when lower(brand) like '%dome%' then 'Domex'
when lower(brand) like '%dove%' then 'Dove'
when lower(brand) like '%dream%' then 'Dreamflower'
when lower(brand) like '%ell %' then 'Ell 18'
when lower(brand) like '%f&l%' then 'Fair & Lovely'
when lower(brand) like '%fal%' then 'Fair & Lovely'
when lower(brand) like '%fl%' then 'Fair & Lovely'
when lower(brand) like '%fair%love%' then 'Fair & Lovely'
when lower(brand) like '%kissan%' then 'Kissan'
when lower(brand) like '%kkt%' then 'KKT'
when lower(brand) like '%knor%' then 'Knorr'
when lower(brand) like '%kwali%' then 'Kwality Wall''s'
when lower(brand) like '%liri%' then 'Liril'
when lower(brand) like '%lakm%' then 'Lakme'
when lower(brand) like '%lifeb%' then 'Lifebuoy'
when lower(brand) like '%lipt%' then 'Lipton'
when lower(brand) like '%lux%' then 'Lux'
when lower(brand) like '%pear%' then 'Pears'
when lower(brand) like '%pepso%' then 'Pepsodent'
when lower(brand) like '%pond%' then 'Ponds'
when lower(brand) like '%pure%' then 'PureIT'
when lower(brand) like '%red%lab%' then 'Red label'
when lower(brand) like '%rin%' then 'Rin'
when lower(brand) like '%sunlig%' then 'Sunlight'
when lower(brand) like '%sunsi%' then 'Sunsilk'
when lower(brand) like '%surf%' then 'Surf Excel'
when lower(brand) like '%taaza%' then 'Taaza'
when lower(brand) like '%taj%' then 'Taj Mahal'
when lower(brand) like '%tigi%' then 'TIGI'
when lower(brand) like '%trese%' then 'Tresemme'
when lower(brand) like '%vaseli%' then 'Vaseline'
when lower(brand) like '%vim%' then 'Vim'
when lower(brand) like '%wheel%' then 'Wheel'
else lower(brand)
end as "Brand",
case when lower(city) like 'bangalu%' then 'Bengaluru'
when lower(city) like 'bangalo%' then 'Bengaluru'
when lower(city) like 'banagal%' then 'Bengaluru'
when lower(city) like 'bengalu%' then 'Bengaluru'
when lower(city) like 'bangalo%' then 'Bengaluru'
when lower(city) like 'bangl%' then 'Bengaluru'
when lower(city) like 'bengl%' then 'Bengaluru'
when lower(city) like 'bango%' then 'Bengaluru'
when lower(city) like 'bangu%' then 'Bengaluru'
when lower(city) like 'blr%' then 'Bengaluru'
when lower(city) like 'bnag%' then 'Bengaluru'
when lower(city) like 'blore%' then 'Bengaluru'
when lower(city) like 'hyder%' then 'Hyderbad'
when lower(city) like 'hydra%' then 'Hyderbad'
when lower(city) like 'puna%' then 'Pune'
when lower(city) like 'poona%' then 'Pune'
when lower(city) like 'pune%' then 'Pune'
when lower(city) like 'ahmed%' then 'Ahemdabad'
when lower(city) like 'ahmad%' then 'Ahemdabad'
when lower(city) like 'ahmd%' then 'Ahemdabad'
when lower(city) like 'aham%' then 'Ahemdabad'
when lower(city) like 'ahem%' then 'Ahemdabad' 
end as City, count(distinct best_mobile_number_hash) from PRM.mindtree_data
where (lower(city) like 'bangalu%' 
or lower(city) like 'bangalo%' 
or lower(city) like 'banagal%' 
or lower(city) like 'bengalu%' 
or lower(city) like 'bangalo%' 
or lower(city) like 'bangl%' 
or lower(city) like 'bengl%' 
or lower(city) like 'bango%' 
or lower(city) like 'bangu%' 
or lower(city) like 'blr%' 
or lower(city) like 'bnag%' 
or lower(city) like 'blore%' 
or lower(city) like 'hyder%' 
or lower(city) like 'hydra%' 
or lower(city) like 'puna%' 
or lower(city) like 'poona%' 
or lower(city) like 'pune%' 
or lower(city) like 'ahmed%' 
or lower(city) like 'ahmad%' 
or lower(city) like 'ahmd%' 
or lower(city) like 'aham%' 
or lower(city) like 'ahem%')
and (lower(brand) like '%3 rose%' 
or lower(brand) like '%axe%' 
or lower(brand) like '%bedhead%' 
or lower(brand) like '%bru%' 
or lower(brand) like '%brook%' 
or lower(brand) like '%clear%' 
or lower(brand) like '%clinic%' 
or lower(brand) like '%close%' 
or lower(brand) like '%comfo%' 
or lower(brand) like '%cornet%' 
or lower(brand) like '%dome%' 
or lower(brand) like '%dove%' 
or lower(brand) like '%dream%' 
or lower(brand) like '%ell %' 
or lower(brand) like '%f&l%' 
or lower(brand) like '%fal%' 
or lower(brand) like '%fl%' 
or lower(brand) like '%fair%love%'
or lower(brand) like '%kissan%' 
or lower(brand) like '%kkt%' 
or lower(brand) like '%knor%' 
or lower(brand) like '%kwali%' 
or lower(brand) like '%liri%' 
or lower(brand) like '%lakm%' 
or lower(brand) like '%lifeb%' 
or lower(brand) like '%lipt%' 
or lower(brand) like '%lux%'  
or lower(brand) like '%pear%' 
or lower(brand) like '%pepso%' 
or lower(brand) like '%pond%' 
or lower(brand) like '%pure%' 
or lower(brand) like '%red%lab%' 
or lower(brand) like '%rin%'  
or lower(brand) like '%sunlig%' 
or lower(brand) like '%sunsi%' 
or lower(brand) like '%surf%' 
or lower(brand) like '%taaza%' 
or lower(brand) like '%taj%'  
or lower(brand) like '%tigi%' 
or lower(brand) like '%trese%' 
or lower(brand) like '%vaseli%' 
or lower(brand) like '%vim%'  
or lower(brand) like '%wheel%')
group by 1,2

union all
select case 
when lower(brand) like '%3 rose%' then '3 Roses'
when lower(brand) like '%axe%' then 'Axe'
when lower(brand) like '%bedhead%' then 'Beadhead'
when lower(brand) like '%bru%' then 'Bru'
when lower(brand) like '%brook%' then 'Brooke Bond'
when lower(brand) like '%clear%' then 'Clear'
when lower(brand) like '%clinic%' then 'Clinic'
when lower(brand) like '%close%' then 'Close UP'
when lower(brand) like '%comfo%' then 'Comfort'
when lower(brand) like '%cornet%' then 'Cornetto'
when lower(brand) like '%dome%' then 'Domex'
when lower(brand) like '%dove%' then 'Dove'
when lower(brand) like '%dream%' then 'Dreamflower'
when lower(brand) like '%ell %' then 'Ell 18'
when lower(brand) like '%f&l%' then 'Fair & Lovely'
when lower(brand) like '%fal%' then 'Fair & Lovely'
when lower(brand) like '%fl%' then 'Fair & Lovely'
when lower(brand) like '%fair%love%' then 'Fair & Lovely'
when lower(brand) like '%kissan%' then 'Kissan'
when lower(brand) like '%kkt%' then 'KKT'
when lower(brand) like '%knor%' then 'Knorr'
when lower(brand) like '%kwali%' then 'Kwality Wall''s'
when lower(brand) like '%liri%' then 'Liril'
when lower(brand) like '%lakm%' then 'Lakme'
when lower(brand) like '%lifeb%' then 'Lifebuoy'
when lower(brand) like '%lipt%' then 'Lipton'
when lower(brand) like '%lux%' then 'Lux'
when lower(brand) like '%pear%' then 'Pears'
when lower(brand) like '%pepso%' then 'Pepsodent'
when lower(brand) like '%pond%' then 'Ponds'
when lower(brand) like '%pure%' then 'PureIT'
when lower(brand) like '%red%lab%' then 'Red label'
when lower(brand) like '%rin%' then 'Rin'
when lower(brand) like '%sunlig%' then 'Sunlight'
when lower(brand) like '%sunsi%' then 'Sunsilk'
when lower(brand) like '%surf%' then 'Surf Excel'
when lower(brand) like '%taaza%' then 'Taaza'
when lower(brand) like '%taj%' then 'Taj Mahal'
when lower(brand) like '%tigi%' then 'TIGI'
when lower(brand) like '%trese%' then 'Tresemme'
when lower(brand) like '%vaseli%' then 'Vaseline'
when lower(brand) like '%vim%' then 'Vim'
when lower(brand) like '%wheel%' then 'Wheel'
else lower(brand)
end as "Brand",
b.region, count(distinct best_mobile_number_hash) from PRM.mindtree_data a
inner join PRM.ref_mobile_lookup b on a.region_lookup_number = b.lookup_prefix5
where  b.region in ('Delhi','Mumbai','Kolkata','Chennai')
and (lower(brand) like '%3 rose%' 
or lower(brand) like '%axe%' 
or lower(brand) like '%bedhead%' 
or lower(brand) like '%bru%' 
or lower(brand) like '%brook%' 
or lower(brand) like '%clear%' 
or lower(brand) like '%clinic%' 
or lower(brand) like '%close%' 
or lower(brand) like '%comfo%' 
or lower(brand) like '%cornet%' 
or lower(brand) like '%dome%' 
or lower(brand) like '%dove%' 
or lower(brand) like '%dream%' 
or lower(brand) like '%ell %' 
or lower(brand) like '%f&l%' 
or lower(brand) like '%fal%' 
or lower(brand) like '%fl%' 
or lower(brand) like '%fair%love%'
or lower(brand) like '%kissan%' 
or lower(brand) like '%kkt%' 
or lower(brand) like '%knor%' 
or lower(brand) like '%kwali%' 
or lower(brand) like '%liri%' 
or lower(brand) like '%lakm%' 
or lower(brand) like '%lifeb%' 
or lower(brand) like '%lipt%' 
or lower(brand) like '%lux%'  
or lower(brand) like '%pear%' 
or lower(brand) like '%pepso%' 
or lower(brand) like '%pond%' 
or lower(brand) like '%pure%' 
or lower(brand) like '%red%lab%' 
or lower(brand) like '%rin%'  
or lower(brand) like '%sunlig%' 
or lower(brand) like '%sunsi%' 
or lower(brand) like '%surf%' 
or lower(brand) like '%taaza%' 
or lower(brand) like '%taj%'  
or lower(brand) like '%tigi%' 
or lower(brand) like '%trese%' 
or lower(brand) like '%vaseli%' 
or lower(brand) like '%vim%'  
or lower(brand) like '%wheel%')
group by 1,2;

--pure it base

select case when lower(city) like 'bangalu%' then 'Bengaluru'
when lower(city) like 'bangalo%' then 'Bengaluru'
when lower(city) like 'banagal%' then 'Bengaluru'
when lower(city) like 'bengalu%' then 'Bengaluru'
when lower(city) like 'bangalo%' then 'Bengaluru'
when lower(city) like 'bangl%' then 'Bengaluru'
when lower(city) like 'bengl%' then 'Bengaluru'
when lower(city) like 'bango%' then 'Bengaluru'
when lower(city) like 'bangu%' then 'Bengaluru'
when lower(city) like 'blr%' then 'Bengaluru'
when lower(city) like 'bnag%' then 'Bengaluru'
when lower(city) like 'blore%' then 'Bengaluru'
when lower(city) like 'hyder%' then 'Hyderbad'
when lower(city) like 'hydra%' then 'Hyderbad'
when lower(city) like 'puna%' then 'Pune'
when lower(city) like 'poona%' then 'Pune'
when lower(city) like 'pune%' then 'Pune'
when lower(city) like 'ahmed%' then 'Ahemdabad'
when lower(city) like 'ahmad%' then 'Ahemdabad'
when lower(city) like 'ahmd%' then 'Ahemdabad'
when lower(city) like 'aham%' then 'Ahemdabad'
when lower(city) like 'ahem%' then 'Ahemdabad' 
end as City, count(distinct best_mobile_number_hash) from PRM.pi_consumer
where (lower(city) like 'bangalu%' 
or lower(city) like 'bangalo%' 
or lower(city) like 'banagal%' 
or lower(city) like 'bengalu%' 
or lower(city) like 'bangalo%' 
or lower(city) like 'bangl%' 
or lower(city) like 'bengl%' 
or lower(city) like 'bango%' 
or lower(city) like 'bangu%' 
or lower(city) like 'blr%' 
or lower(city) like 'bnag%' 
or lower(city) like 'blore%' 
or lower(city) like 'hyder%' 
or lower(city) like 'hydra%' 
or lower(city) like 'puna%' 
or lower(city) like 'poona%' 
or lower(city) like 'pune%' 
or lower(city) like 'ahmed%' 
or lower(city) like 'ahmad%' 
or lower(city) like 'ahmd%' 
or lower(city) like 'aham%' 
or lower(city) like 'ahem%')
group by 1

union all
select b.region, count(distinct best_mobile_number_hash) from PRM.pi_consumer a
inner join PRM.ref_mobile_lookup b on a.region_lookup_number = b.lookup_prefix5
where  b.region in ('Delhi','Mumbai','Kolkata','Chennai')
group by 1;


--region --brand
lower(city) like 'bangalu%' 
or lower(city) like 'bangalo%' 
or lower(city) like 'banagal%' 
or lower(city) like 'bengalu%' 
or lower(city) like 'bangalo%' 
or lower(city) like 'bangl%' 
or lower(city) like 'bengl%' 
or lower(city) like 'bango%' 
or lower(city) like 'bangu%' 
or lower(city) like 'blr%' 
or lower(city) like 'bnag%' 
or lower(city) like 'blore%' 
or lower(city) like 'hyder%' 
or lower(city) like 'hydra%' 
or lower(city) like 'puna%' 
or lower(city) like 'poona%' 
or lower(city) like 'pune%' 
or lower(city) like 'ahmed%' 
or lower(city) like 'ahmad%' 
or lower(city) like 'ahmd%' 
or lower(city) like 'aham%' 
or lower(city) like 'ahem%' 


(lower(brand) like '%3 rose%' 
or lower(brand) like '%axe%' 
or lower(brand) like '%bedhead%' 
or lower(brand) like '%bru%' 
or lower(brand) like '%brook%' 
or lower(brand) like '%clear%' 
or lower(brand) like '%clinic%' 
or lower(brand) like '%close%' 
or lower(brand) like '%comfo%' 
or lower(brand) like '%cornet%' 
or lower(brand) like '%dome%' 
or lower(brand) like '%dove%' 
or lower(brand) like '%dream%' 
or lower(brand) like '%ell %' 
or lower(brand) like '%f&l%' 
or lower(brand) like '%fal%' 
or lower(brand) like '%fl%' 
or lower(brand) like '%fair%love%'
or lower(brand) like '%kissan%' 
or lower(brand) like '%kkt%' 
or lower(brand) like '%knor%' 
or lower(brand) like '%kwali%' 
or lower(brand) like '%liri%' 
or lower(brand) like '%lakm%' 
or lower(brand) like '%lifeb%' 
or lower(brand) like '%lipt%' 
or lower(brand) like '%lux%'  
or lower(brand) like '%pear%' 
or lower(brand) like '%pepso%' 
or lower(brand) like '%pond%' 
or lower(brand) like '%pure%' 
or lower(brand) like '%red%lab%' 
or lower(brand) like '%rin%'  
or lower(brand) like '%sunlig%' 
or lower(brand) like '%sunsi%' 
or lower(brand) like '%surf%' 
or lower(brand) like '%taaza%' 
or lower(brand) like '%taj%'  
or lower(brand) like '%tigi%' 
or lower(brand) like '%trese%' 
or lower(brand) like '%vaseli%' 
or lower(brand) like '%vim%'  
or lower(brand) like '%wheel%')






-- from bt and dl tables






